export enum TargetCondition {
  ALL_CLIENTS_THIS_MONTH,
  ALL_CLIENTS_THIS_YEAR,
  ALL_CLIENTS_FROM_1_MONTH,
  ALL_CLIENTS_FROM_2_MONTHS,
  ALL_CLIENTS_FROM_3_MONTHS,
  ALL_CLIENTS_FROM_6_MONTHS,
  ALL_CLIENTS_FROM_LAST_YEAR,
}
